WeatherExerciseDependencyInjection/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using System.Diagnostics.Eventing.Reader;
using WeatherExerciseDependencyInjection.Interfaces;
using WeatherExerciseDependencyInjection.Models;


namespace WeatherExerciseDependencyInjection.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWeatherLogic _weatherLogic;
        private readonly IDougsTest _doug;
        public HomeController(IWeatherLogic weatherBll, IDougsTest doug)
        {
            _weatherLogic = weatherBll;
            _doug = doug;
            _doug.Name += "Home ";
            _doug.Count += 1;

            _doug.Description = "Born in the constructor of the Controller.";
        }

        [Route("/")]
        [Route("home")]
        public IActionResult Index()
        {
            ViewBag.Title = "Weather App";
            ViewBag.Doug = _doug.ToString();
            ViewBag.DougTime = _doug.GetCurrentDate();

            var viewData = _weatherLogic.GetWeatherData();
            return View(viewData);

        }


        [Route("/details/{citycode}")]
        public IActionResult Details(string cityCode)
        {
             ViewBag.Title = "Weather Details";
            ViewBag.IsDetails = true;
            if (cityCode != null)
            {
                ICityWeather? cityWeather = _weatherLogic.GetWeatherData().Where(w => w.CityUniqueCode == cityCode).FirstOrDefault();
                if (cityWeather == null)
                {
                    return BadRequest("Invalid City Code");
                }
                return View(cityWeather);
            }
            else
            {
                return BadRequest("Supply City Code");
            }

        }
        [Route("/get-weather/{citycode}")]
        public IActionResult GetWeather(string cityCode)
        {
            ViewBag.Title = "Weather Details";
            ViewBag.IsDetails = true;
            if (cityCode != null)
            {
                ICityWeather? cityWeather = _weatherLogic. GetWeatherData().Where(w => w.CityUniqueCode == cityCode).FirstOrDefault();
                if (cityWeather == null)
                {
                    return BadRequest("Invalid City Code");
                }
                return ViewComponent("Tile", cityWeather);
            }
            else
            {
                return BadRequest("Supply City Code");
            }

        }
    }
}

WeatherExerciseDependencyInjection/ViewComponents/TileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WeatherExerciseDependencyInjection.Interfaces;
using WeatherExerciseDependencyInjection.Models;

namespace WeatherExerciseDependencyInjection.Presentation.Components
{
    public class TileViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CityWeather cityWeather)
        {
            return View(cityWeather);
        }
    }
}

WeatherExerciseDependencyInjection/Views/Home/Details.cshtml
@model ICityWeather

<br />

<div class="box w-50 center">
    <div class="row center" >
       @*  <vc:tile city-weather="@Model"> </vc:tile> *@
        @await Component.InvokeAsync("Tile", Model)
    </div>
</div>
<br />
<div class="text-center">
    <a href="/">Back to Weather Home Page</a>
</div>
<br />
<div class="text-center">
    <button class="button button-blue-back" id="load-weather">Get Weather</button>
    <div class="w-50 center" id="weather-details"></div>
</div> 



<script>
    document.querySelector("#load-weather").addEventListener("click", async function () {
        var response = await fetch("/get-weather/@Model.CityUniqueCode", { method: "GET" });
        var responseBody = await response.text();
        document.querySelector("#weather-details").innerHTML = responseBody;
    });

</script>

WeatherExerciseDependencyInjection/Views/Home/Index.cshtml
@model List<ICityWeather>
<partial name="_cityWeatherPartialView"/>

<div class="box bg-coldest w-50 center" >
    <p>Doug: @ViewBag.Doug</p>
    <p>Time: @ViewBag.DougTime</p>

</div>

WeatherExerciseDependencyInjection/Views/Shared/Components/Tile/Default.cshtml
@model ICityWeather


<div class="box w-100 @Model.TemperatureColor">
    <div class="column center w-100" >
        <h2>@Model.CityName</h2>
        <h4>@Model.CurrentDateTime</h4>
        @if (ViewBag.IsDetails!=true)
        {
           <div class="center w-100"><a class="center w-100" href="/details/@Model.CityUniqueCode">Details</a></div>
        }
    </div>
    <div class="column border-top text-center">
        <h1> @Model.Temperature<sup class="text-silver">&deg;F</sup></h1>
    </div>
</div> 

WeatherExerciseDependencyInjection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>ViewBag.appTitle</title>
    <meta charset="utf-8" />
    <link href="~/StyleSheet.css" rel="stylesheet" />

</head>
<body>
    <div class="page-content w-100 center">
        <h1 class="header ">Weather</h1>
            @RenderBody()
    </div>
</body>

</html>

WeatherExerciseDependencyInjection/Views/Shared/_cityWeatherPartialView.cshtml
@model List<ICityWeather>

<div class="row">
    @foreach (var item in Model)
    {
      <!--<vc:tile city-weather="item"> </vc:tile>-->
        @await Component.InvokeAsync("Tile", item)
    }
</div> 